### ISSUE TITLE
Add support for other Python versions

### ISSUE THREAD

**Issue by gaby** [James-Ansley/cowexcept#1]
@James-Ansley Currently this very useful library is only supporting py3.10, would it be possible to make it work with py3.8, py3.9, and py3.11 ? Those versions of python are still getting updates.

Thanks!

**Comment by James-Ansley** [comment]
Thank you for the suggestion. I have added support for Python 3.8+. Hopefully, this very useful library will now be able to be useful on even more Python versions.

**Comment by gaby** [comment]
@James-Ansley Thank you! 🙌
